<template>
    <span
        role="checkbox"
        aria-labelledby="test"
        tabindex="0"
    />
    <span
        role="radio"
        aria-labelledby="test"
        tabindex="0"
    />
</template>
