module.exports = {
    correct: [
        './correct/correct-1.vue',
        './correct/correct-2.vue',
        './correct/correct-3.vue',
        './correct/correct-4.vue',
        './correct/correct-5.vue',
        './correct/correct-6.vue',
        './correct/correct-7.vue',
        './correct/correct-8.vue',
        './correct/correct-9.vue',
        './correct/correct-10.vue',
        './correct/correct-11.vue',
        './correct/correct-12.vue',
        './correct/correct-13.vue',
        './correct/correct-14.vue',
        './correct/correct-15.vue',
        './correct/correct-16.vue',
        './correct/correct-17.vue',
        './correct/correct-18.vue',
        './correct/correct-19.vue',
        './correct/correct-20.vue',
    ],
    incorrect: [
        './incorrect/incorrect-1.vue',
        './incorrect/incorrect-2.vue',
        './incorrect/incorrect-3.vue',
        './incorrect/incorrect-4.vue',
        './incorrect/incorrect-5.vue',
        './incorrect/incorrect-6.vue',
        './incorrect/incorrect-7.vue',
        './incorrect/incorrect-8.vue',
        './incorrect/incorrect-9.vue',
        './incorrect/incorrect-10.vue',
        './incorrect/incorrect-11.vue',
    ],
};
