name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: [ubuntu-latest]
        timeout-minutes: 15
        steps:
            -   name: Reset permissions
                run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

            -   name: Checkout
                uses: actions/checkout@master

            -   name: Use Node.js
                uses: actions/setup-node@v2-beta
                with:
                    node-version: 14

            -   name: Install yarn
                run: npm install -g yarn

            -   name: Build
                run: |
                    yarn
                    yarn build

            -   name: Build and Deploy
                uses: JamesIves/github-pages-deploy-action@4.1.1
                with:
                    branch: gh-pages # The branch the action should deploy to.
                    folder: docs # The folder the action should deploy.

            -   name: Uninstall yarn
                run: npm uninstall -g yarn
