name: Run tests
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lerna bootstrap
      - run: yarn test
